# Generated by Django 5.0.2 on 2024-02-27 22:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('SERVICE', 'Service'), ('PRODUCTION', 'Production'), ('OTHER', 'Other')], default='OTHER', max_length=10, verbose_name='Company Type')),
                ('name', models.CharField(error_messages={'unique': 'Company with this name already exists. Choose another one'}, help_text='Field is required', max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='Cannot have less than 3 characters')])),
                ('founded_date', models.DateField(auto_now_add=True)),
                ('headquarters_location', models.CharField(blank=True, help_text='Field is required. Set the locations of the headquarters', max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
