# Generated by Django 5.0.2 on 2024-03-29 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_headquarters_location_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2, message='Location name cannot have less than 2 characters. Try to add continent, country and city')]),
        ),
    ]
