# Generated by Django 5.0.2 on 2024-03-30 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_location_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('SERVICE', 'Service'), ('PRODUCTION', 'Production'), ('BASE', 'Base')], default='BASE', max_length=10, verbose_name='Company Type'),
        ),
    ]
