# Generated by Django 5.0.2 on 2024-03-30 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_owner_alter_company_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='modified',
            new_name='last_modified',
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 3, 30, 9, 13, 29, 221223, tzinfo=datetime.timezone.utc), editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
