# Generated by Django 5.0.2 on 2024-03-30 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountsuser_modified'),
        ('company', '0005_rename_modified_company_last_modified_company_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='accounts.profile'),
        ),
    ]
