# Generated by Django 5.0.4 on 2024-04-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_company_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
