# Generated by Django 5.0.2 on 2024-04-02 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
        ('processes', '0003_alter_process_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(default='Add description')),
                ('duration_days', models.PositiveIntegerField(blank=True, default=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='procedure',
        ),
        migrations.AddField(
            model_name='procedure',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='name',
            field=models.CharField(default='some_name', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedure',
            name='owner',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedure',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='processes', to='processes.process'),
        ),
        migrations.CreateModel(
            name='RelationProcedureTaskTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.procedure')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.proceduretask')),
            ],
        ),
    ]
