# Generated by Django 5.0.2 on 2024-04-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0002_proceduretask_remove_procedure_procedure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationproceduretasktask',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='relationproceduretasktask',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
