# Generated by Django 5.0.2 on 2024-04-02 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0003_remove_relationproceduretasktask_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 2, 20, 57, 52, 715289, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proceduretask',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 2, 20, 57, 55, 114394, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationproceduretasktask',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 2, 20, 57, 57, 371108, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
