# Generated by Django 5.0.2 on 2024-03-29 11:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(10, message='Cannot have less than 40 characters')])),
                ('description', models.TextField(help_text='Enter instruction description')),
                ('procedures', models.ManyToManyField(related_name='instructions', to='procedures.procedure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstructionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('step_type', models.CharField(choices=[('EXECUTE', 'Execute'), ('IF_BLOCK', 'If Block'), ('TO_PROCESS', 'To Process'), ('END_BLOCK', 'End Block')], max_length=10)),
                ('step_label', models.CharField(max_length=20)),
                ('step_text', models.CharField(choices=[('EXECUTE', 'Execute'), ('IF_BLOCK', 'If Block'), ('TO_PROCESS', 'To Process'), ('END_BLOCK', 'End Block')], max_length=10)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='instructions.instruction')),
            ],
        ),
    ]
