# Generated by Django 5.0.2 on 2024-04-02 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='owner',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructionstep',
            name='step_label',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='instructionstep',
            name='step_text',
            field=models.CharField(choices=[('START_BLOCK', 'Start Block'), ('EXECUTE', 'Execute'), ('IF_BLOCK', 'If Block'), ('TO_PROCESS', 'To Process'), ('END_BLOCK', 'End Block')], max_length=11),
        ),
        migrations.AlterField(
            model_name='instructionstep',
            name='step_type',
            field=models.CharField(choices=[('START_BLOCK', 'Start Block'), ('EXECUTE', 'Execute'), ('IF_BLOCK', 'If Block'), ('TO_PROCESS', 'To Process'), ('END_BLOCK', 'End Block')], max_length=11),
        ),
    ]
