# Generated by Django 5.0.2 on 2024-04-02 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0002_instruction_owner_alter_instructionstep_step_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 2, 20, 57, 48, 954960, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
