# Generated by Django 5.0.4 on 2024-04-11 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0003_instruction_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstructionStep',
        ),
    ]
