# Generated by Django 5.0.2 on 2024-02-27 22:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(error_messages={'unique': 'Activity with this title already exists, Include department name in the title.         Example: "title"-"Department name"'}, help_text='Field is required.', max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Cannot have less than 5 characters')])),
                ('description', models.TextField(help_text='Field is required. Enter a brief description of the activity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
