# Generated by Django 5.0.2 on 2024-03-31 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(help_text='Enter a brief description of the activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(error_messages={'unique': 'Activity with this title already exists, Include department name in the title.         Example: "title"-"Department name"'}, max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Cannot have less than 5 characters')]),
        ),
    ]
