# Generated by Django 5.0.2 on 2024-04-02 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 2, 20, 57, 36, 98739, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
