# Generated by Django 5.0.4 on 2024-04-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activity_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
