# Generated by Django 5.0.2 on 2024-02-27 22:46

import CPDM.validators.accounts_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(error_messages={'unique': 'Username already exists. Please choose a different one'}, help_text='Field is required.\nEnsure username contains only letters, numbers, and underscores.', max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='Cannot have less than 2 characters'), CPDM.validators.accounts_validators.validate_username])),
                ('first_name', models.CharField(help_text='Field is required', max_length=15, validators=[django.core.validators.MinLengthValidator(3, message='Cannot have less than 3 characters')])),
                ('last_name', models.CharField(help_text='Field is required', max_length=15, validators=[django.core.validators.MinLengthValidator(3, message='Cannot have less than 6 characters')])),
                ('password', models.CharField(help_text='Field is required. Password must be at least 6 characters long.\n         Password must contain at least 2 special characters, one capital letter.', max_length=30, validators=[django.core.validators.MinLengthValidator(6, message='Cannot have less than 6 characters')])),
                ('email', models.EmailField(help_text='Field is required', max_length=254)),
                ('slug', models.SlugField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
