# Generated by Django 5.0.2 on 2024-03-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsuser',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
