# Generated by Django 5.0.4 on 2024-04-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountsuser_created_profile_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsuser',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
