# Generated by Django 5.0.2 on 2024-03-29 11:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(6, message='Cannot have less than 20 characters')])),
                ('description', models.TextField(help_text='Enter Process description. Include Activities and Departments')),
                ('activities', models.ManyToManyField(related_name='processes', to='activities.activity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('step_type', models.CharField(choices=[('EXECUTE', 'Execute'), ('IF_BLOCK', 'If Block'), ('TO_PROCESS', 'To Process'), ('END_BLOCK', 'End Block')], max_length=10)),
                ('step_label', models.CharField(max_length=20)),
                ('step_text', models.CharField(choices=[('EXECUTE', 'Execute'), ('IF_BLOCK', 'If Block'), ('TO_PROCESS', 'To Process'), ('END_BLOCK', 'End Block')], max_length=10)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='processes.process')),
            ],
        ),
    ]
