# Generated by Django 5.0.2 on 2024-03-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processstep',
            old_name='instruction',
            new_name='process',
        ),
    ]
