# Generated by Django 5.0.2 on 2024-04-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_remove_processstep_step_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processstep',
            old_name='step_text',
            new_name='step_label',
        ),
    ]
