# Generated by Django 5.0.4 on 2024-04-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_rename_step_text_processstep_step_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name_plural': 'Processes'},
        ),
    ]
