# Generated by Django 5.0.2 on 2024-03-29 11:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(error_messages={'unique': 'Software with this name already exists. Choose another one'}, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='Cannot have less than 3 characters')])),
                ('version', models.CharField(help_text='Field is required. Include software version', max_length=20)),
                ('license', models.CharField(help_text='Field is required. Include software license name and number', max_length=30, validators=[django.core.validators.MinLengthValidator(4, message='Cannot have less than 4 characters')])),
                ('vendor', models.URLField(help_text='Field is required. Include software vendor URL', max_length=30, validators=[django.core.validators.MinLengthValidator(7, message='Cannot have less than 7 characters')])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software', to='company.company')),
                ('departments', models.ManyToManyField(related_name='software_departments', to='departments.department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
