# Generated by Django 5.0.2 on 2024-04-03 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountsuser_created_profile_created'),
        ('software', '0002_software_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
            preserve_default=False,
        ),
    ]
