# Generated by Django 5.0.2 on 2024-04-03 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_alter_software_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='vendor',
            field=models.URLField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(7, message='Cannot have less than 7 characters')]),
        ),
    ]
