# Generated by Django 5.0.4 on 2024-04-13 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0006_alter_software_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name_plural': 'Software'},
        ),
        migrations.AlterField(
            model_name='software',
            name='license',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4, message='Cannot have less than 4 characters')]),
        ),
        migrations.AlterField(
            model_name='software',
            name='version',
            field=models.CharField(max_length=20),
        ),
    ]
