# Generated by Django 5.0.2 on 2024-03-30 17:56

import CPDM.employees.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3, message='First Name must be at least 15 characters long'), CPDM.employees.validators.validate_employee_first_name])),
                ('last_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3, message='First Name must be at least 15 characters long'), CPDM.employees.validators.validate_employee_last_name])),
            ],
        ),
    ]
