# Generated by Django 5.0.2 on 2024-03-30 19:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_owner'),
        ('departments', '0003_department_company'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, related_name='employees_companies', to='company.company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='company_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, related_name='employees_departments', to='departments.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, help_text='Enter seniority and position', max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3, message='Title must be at least 3 characters long')]),
        ),
    ]
