# Generated by Django 5.0.2 on 2024-03-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_owner'),
        ('departments', '0004_alter_department_activities_and_more'),
        ('employees', '0002_employee_company_employee_company_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ManyToManyField(related_name='employees_companies', to='company.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ManyToManyField(related_name='employees_departments', to='departments.department'),
        ),
    ]
