# Generated by Django 5.0.2 on 2024-03-29 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(error_messages={'unique': 'Department with this name already exists. Include Department location,         Example: "Department name"-"Department location"'}, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='Cannot have less than 2 characters')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
