# Generated by Django 5.0.2 on 2024-03-31 19:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0003_alter_activity_description_alter_activity_title'),
        ('company', '0008_alter_company_name'),
        ('processes', '0002_rename_instruction_processstep_process'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(error_messages={'unique': 'Department with this name already exists. Include Department location,         Example: "Department name"-"Department location"'}, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='Cannot have less than 2 characters')])),
                ('activities', models.ManyToManyField(related_name='departments_in_activity', to='activities.activity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='company.company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to=settings.AUTH_USER_MODEL)),
                ('processes', models.ManyToManyField(related_name='departments_in_process', to='processes.process')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
