# Generated by Django 5.0.2 on 2024-03-30 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_owner'),
        ('departments', '0001_initial'),
        ('processes', '0002_rename_instruction_processstep_process'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='activities',
            field=models.ManyToManyField(blank=True, null=True, related_name='departments_in_activity', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='department',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='processes',
            field=models.ManyToManyField(blank=True, null=True, related_name='departments_in_process', to='processes.process'),
        ),
    ]
