# Generated by Django 5.0.2 on 2024-03-30 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_owner'),
        ('departments', '0002_department_activities_department_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='company.company'),
            preserve_default=False,
        ),
    ]
