# Generated by Django 5.0.2 on 2024-03-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_owner'),
        ('departments', '0003_department_company'),
        ('processes', '0002_rename_instruction_processstep_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='activities',
            field=models.ManyToManyField(related_name='departments_in_activity', to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='department',
            name='processes',
            field=models.ManyToManyField(related_name='departments_in_process', to='processes.process'),
        ),
    ]
